query GetAccounts {
  accounts {
    id
    displayName
    type {
      name
      display
      group
    }
    subtype {
      name
      display
    }
    displayBalance
    currentBalance
    limit
    dataProviderCreditLimit
    updatedAt
    displayLastUpdatedAt
    deactivatedAt
    isHidden
    isAsset
    mask
    createdAt
    includeInNetWorth
    hideFromList
    hideTransactionsFromReports
    includeBalanceInNetWorth
    includeInGoalBalance
    dataProvider
    dataProviderAccountId
    isManual
    transactionsCount
    manualInvestmentsTrackingMethod
    order
    icon
    logoUrl
    credential {
      id
      updateRequired
      disconnectedFromDataProviderAt
      dataProvider
      institution {
        id
        plaidInstitutionId
        name
        status
      }
    }
  }
  householdPreferences {
    id
    accountGroupOrder
  }
}
